### ISSUE TITLE
Error occurs when trying to get Metric containing "."

### ISSUE THREAD

**Issue by inulin1212** [fengxsong/aliyun_exporter#7]
Error occurs when trying to get Metric containing "." Such as net.rx of acs_vpc_eip。
Is there a workaround? 

--------------------------
panic: "cloudmonitor_acs_vpc_eip_net.rx" is not a valid metric name

goroutine 13 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/value.go:107
github.com/fengxsong/aliyun-exporter/pkg/client.(*MetricClient).Collect(0xc0002803a0, 0x1bed4e8, 0xc, 0xc0000b94f0, 0xb, 0xc0000a8c60, 0xc00008d260)
        /workspace/pkg/client/metric.go:148 +0x6ca
github.com/fengxsong/aliyun-exporter/pkg/collector.(*cloudMonitor).Collect.func1(0xc000045c40, 0xc0000b6e00, 0xc00008d260, 0xc0000b94f0, 0xb, 0xc0000a8c60)
        /workspace/pkg/collector/collector.go:68 +0xe5
created by github.com/fengxsong/aliyun-exporter/pkg/collector.(*cloudMonitor).Collect
        /workspace/pkg/collector/collector.go:65 +0x179

**Comment by fengxsong** [comment]
currently i have not ak/sk for testing. could you paste your configuration here? @inulin1212

**Comment by fengxsong** [comment]
or maybe you can set alias, for example

```
...
metrics:
  acs_elasticsearch:
  - desc: nothing special
    dimensions:
    - userId
    - clusterId
    measure: Maximum
    name: someMetricsWithDot.test
    alias: some_metrics_with_dot_test # add alias here
    period: 60
    unit: value
```

@inulin1212

**Comment by inulin1212** [comment]
configuration are like this.
```
  acs_vpc_eip:
  - desc: EIP.net.rx
    dimensions:
    - userId
    - instanceId
    measure: Average
    name: net.rx
    period: 60
    unit: bytes
```
I referred to the URL below
https://www.alibabacloud.com/help/doc-detail/162874.htm
